version: '2'

services:
  user_search_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
    volumes:
      - ./db/user_search_mongo_db:/data/db
  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: welcome
  vehicle_info_db:
    image: postgres
    restart: always
    ports:
      - 5402:5432
    environment:
      POSTGRES_DB: vehicle_info_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: welcome
    volumes:
      - ./db/vehicle_info_db:/var/lib/postgresql/data
  user_db:
    image: postgres
    restart: always
    ports:
      - 5403:5432
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: welcome
    volumes:
      - ./db/user_db:/var/lib/postgresql/data
  session_db:
    image: postgres
    restart: always
    ports:
      - 5404:5432
    environment:
      POSTGRES_DB: session_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: welcome
    volumes:
      - ./db/session_db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: welcome
    volumes:
      - ./db/rabbit:/var/lib/rabbitmq